/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { QRDesignConfig } from '../types';

export const DEFAULT_DESIGN_CONFIG: QRDesignConfig = {
  id: 'default',
  name: 'Ocean Breeze',
  patternStyle: 'smooth',
  eyeStyleOuter: 'rounded',
  eyeStyleInner: 'circle',
  foreground: {
    type: 'gradient',
    solidColor: '#2563EB',
    gradientType: 'linear',
    gradientColor1: '#2563EB',
    gradientColor2: '#0D9488',
    gradientRotation: 45,
  },
  background: '#FFFFFF',
  errorCorrection: 'H',
  logo: {
    src: '',
    scale: 0.18,
    padding: 1.5,
    backgroundColor: '#FFFFFF',
    shape: 'circle',
  },
  margin: 3,
};

export const PRESET_TEMPLATES: QRDesignConfig[] = [
  {
    id: 'ocean-breeze',
    name: 'Ocean Breeze',
    patternStyle: 'smooth',
    eyeStyleOuter: 'rounded',
    eyeStyleInner: 'circle',
    foreground: {
      type: 'gradient',
      solidColor: '#2563EB',
      gradientType: 'linear',
      gradientColor1: '#2563EB',
      gradientColor2: '#0D9488',
      gradientRotation: 45,
    },
    background: '#FFFFFF',
    errorCorrection: 'H',
    logo: {
      src: '',
      scale: 0.18,
      padding: 1.5,
      backgroundColor: '#FFFFFF',
      shape: 'circle',
    },
    margin: 3,
  },
  {
    id: 'emerald-leaf',
    name: 'Emerald Garden',
    patternStyle: 'extra-rounded',
    eyeStyleOuter: 'leaf',
    eyeStyleInner: 'leaf',
    foreground: {
      type: 'gradient',
      solidColor: '#059669',
      gradientType: 'linear',
      gradientColor1: '#059669',
      gradientColor2: '#10B981',
      gradientRotation: 135,
    },
    background: '#FFFFFF',
    errorCorrection: 'H',
    logo: {
      src: '',
      scale: 0.18,
      padding: 2,
      backgroundColor: '#FFFFFF',
      shape: 'rounded',
    },
    margin: 3,
  },
  {
    id: 'midnight-tech',
    name: 'Midnight Cyber',
    patternStyle: 'dots',
    eyeStyleOuter: 'circle',
    eyeStyleInner: 'circle',
    foreground: {
      type: 'gradient',
      solidColor: '#4F46E5',
      gradientType: 'radial',
      gradientColor1: '#EC4899',
      gradientColor2: '#4F46E5',
      gradientRotation: 0,
    },
    background: '#090D16',
    errorCorrection: 'Q',
    logo: {
      src: '',
      scale: 0.18,
      padding: 1.5,
      backgroundColor: '#090D16',
      shape: 'circle',
    },
    margin: 3,
  },
  {
    id: 'sunset-essence',
    name: 'Tangerine Dream',
    patternStyle: 'dots',
    eyeStyleOuter: 'rounded',
    eyeStyleInner: 'square',
    foreground: {
      type: 'gradient',
      solidColor: '#EA580C',
      gradientType: 'linear',
      gradientColor1: '#F43F5E',
      gradientColor2: '#EAB308',
      gradientRotation: 30,
    },
    background: '#FFFFFF',
    errorCorrection: 'H',
    logo: {
      src: '',
      scale: 0.18,
      padding: 1,
      backgroundColor: '#FFFFFF',
      shape: 'circle',
    },
    margin: 3,
  },
  {
    id: 'classic-dark',
    name: 'Monochrome Luxe',
    patternStyle: 'squares',
    eyeStyleOuter: 'square',
    eyeStyleInner: 'square',
    foreground: {
      type: 'solid',
      solidColor: '#1E293B',
      gradientType: 'linear',
      gradientColor1: '#1E293B',
      gradientColor2: '#0F172A',
      gradientRotation: 0,
    },
    background: '#FFFFFF',
    errorCorrection: 'M',
    logo: {
      src: '',
      scale: 0.16,
      padding: 2,
      backgroundColor: '#FFFFFF',
      shape: 'square',
    },
    margin: 3,
  }
];
